# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('a_id', models.ManyToManyField(to='charchitra.Actor')),
                ('g_id', models.ManyToManyField(to='charchitra.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPackPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charchitra.Actor')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charchitra.Duration')),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charchitra.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charchitra.Duration')),
                ('v_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charchitra.Video')),
            ],
        ),
    ]
