# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charchitra', '0002_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='is_pack',
            field=models.NullBooleanField(default=False),
        ),
    ]
