# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charchitra', '0004_auto_20190212_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
