# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charchitra', '0005_video_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprice',
            name='dur_name',
            field=models.CharField(default='d', max_length=40),
        ),
    ]
