# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charchitra', '0007_auto_20190212_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoprice',
            name='v_id',
        ),
        migrations.DeleteModel(
            name='VideoPrice',
        ),
    ]
