# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charchitra', '0011_videoprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprice',
            name='dur_name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
