# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charchitra', '0013_auto_20190212_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopackprice',
            name='dur_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='videoprice',
            name='dur_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='videopackprice',
            unique_together=set([('a_id', 'g_id', 'dur_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='videoprice',
            unique_together=set([('v_id', 'dur_name')]),
        ),
    ]
