# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charchitra', '0014_auto_20190212_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='p_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charchitra.VideoPackPrice'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='v_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charchitra.Video'),
        ),
        migrations.AlterField(
            model_name='videopackprice',
            name='dur_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
