# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charchitra', '0015_auto_20190213_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='p_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charchitra.VideoPackPrice'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='v_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charchitra.Video'),
        ),
    ]
