# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charchitra', '0016_auto_20190213_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopackprice',
            name='pack_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
