# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
